### ISSUE TITLE
Pause but don't end monitoring when I get up briefly

### ISSUE THREAD

**Issue by carlin-q-scott** [lnenad/slouch-stoppah#1]
I get up frequently for short period of time (~1 minute), and have to open the slouch stopah tab to resume monitoring each time I sit down again. It would be nice if it automatically resumed after detecting my face again.

**Comment by Samir-Rashid** [comment]
This is intentional behavior. It is to save energy as face detection is relatively cpu heavy. 
You can fix this if you edit `app.js` and simply delete this code to stop the camera. You would then have to statically host the edited code yourself. 

```js
        noFace++;
        if (noFace > 5) {
            displayError("Tracking stopped because we are unable to detect a face. Maybe increase light intensity?");
            stopCamera();
            return;
        }
```


Let me know if this fixes your issue. 
Edit: A better solution would be to just increase the noface timeout by 10x or so.

**Comment by lnenad** [comment]
Exactly what @Samir-Rashid wrote, it would be easy to add a checkbox to disable this behavior.

**Comment by carlin-q-scott** [comment]
Would this project welcome a PR that added a bathroom break detection algorithm? It would work something like this:
1. No face for interval * 5 (current implementation)
2. Detection interval relaxed to 15s while waiting for face to reappear for up to 2 minutes
3. Resume normal operation if face reappears
4. Disable detection if no face still after 2 minutes

**Comment by lnenad** [comment]
@carlin-q-scott of course it would!
